name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        cd server && npm install
        cd ../client && npm install
    
    - name: Build application
      run: |
        cd client && npm run build
    
    - name: Prepare deployment package
      run: |
        mkdir -p deploy/server
        mkdir -p deploy/client
        cp -r server/* deploy/server/
        cp -r client/dist deploy/client/
        cp server/package.json deploy/server/
        cp server/package-lock.json deploy/server/ || true
        cd deploy/server && npm install --production
        cd ..
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'family-workout-challenge'
        package: './deploy/server'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

